name: Scrape Competitor Promotions

on:
  schedule:
    - cron: '0 22 * * *' # Runs daily at 22:00 UTC (5:00 AM JST)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- THIS IS THE NEW, MORE RELIABLE METHOD ---
      # It replaces the entire "Install Chrome Dependencies" block
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium beautifulsoup4

      - name: Run Scraper
        env:
          JSONBIN_URL: ${{ secrets.JSONBIN_URL }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
        run: python scraper_sg.py
