name: Scrape Competitor Promotions

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox geckodriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium beautifulsoup4

      - name: Run Scraper Diagnostic
        env:
          JSONBIN_URL: ${{ secrets.JSONBIN_URL }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
        run: python scraper_sg.py

      # This step will save our debug files
      - name: Upload Artifacts
        if: always() # This ensures it runs even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            debug_*.png
            debug_*.html
