name: Scrape Competitor Promotions

on:
  schedule:
    - cron: '0 22 * * *' # Runs daily at 22:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium beautifulsoup4

      # THIS IS THE NEW STEP YOU NEED TO ADD
      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libgconf-2-4 libfontconfig1 libxss1

      - name: Run Scraper
        env:
          JSONBIN_URL: ${{ secrets.JSONBIN_URL }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
          CHROME_BIN: /usr/bin/google-chrome # Make sure Chrome is available
        run: python scraper_sg.py
