name: Scrape Competitor Promotions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # NEW: We will use a dedicated action to install Chrome properly
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run scraper and update data
        env:
          JSONBIN_URL: ${{ secrets.JSONBIN_URL }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
          # NEW: Pass the location of the installed Chrome browser to the script
          CHROME_EXECUTABLE_PATH: ${{ env.CHROME_BIN }}
        run: python scraper_sg.py
